steps:
  # Step 1: Check out the code
  #- name: 'gcr.io/cloud-builders/git'
  #  args: ['clone', 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME.git', '.']

  # Step 2: Set up JDK (since Maven requires JDK)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'apt-get update && apt-get install -y openjdk-17-jdk']

  # Step 3: Run Maven to build the project
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install', '-DskipTests']

  # Step 4: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

  # Step 5: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    #args: ['push', 'gcr.io/$PROJECT_ID/my-app']
    args: ['push', 'arshad849/nagp-assignment/myapp:latest']

images:
  #- 'gcr.io/$PROJECT_ID/my-app'
  - 'arshad849/nagp-assignment/myapp'

logsBucket: "gs://cloudbuild-logs-bucket-arshad"
