apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  #replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          #image: gcr.io/nagp-assignment-kubernetes/my-app:v12
          image: docker.io/arshad849/nagp-assignment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: config-volume
          configMap:
            name: app-config
            items:
              - key: application.properties
                path: application.properties
