apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  database-name: mydb

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHVzZXI=
  mysql-user: dXNlcg==
  mysql-password: cGFzc3dvcmQ=
